### PR TITLE
Switched to AsyncKeyedLock library

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This gives better performance and reduced memory allocations.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@donaldgray will this need to wait just like https://github.com/dlcs/protagonist/pull/435 ? They're very related.

**Comment by MarkCiliaVincenti** [comment]
@donaldgray ?

**Comment by donaldgray** [comment]
Morning @MarkCiliaVincenti - Thanks for opening this PR, it is appreciated but we have discussed this change internally and decided against pulling it in.

The `AsyncKeyedLock` class we have is an intentionally naive implementation that has been used in a very high-traffic production system for almost 2 years without issue so we will stick with this for now and avoid pulling in an additional dependency.

**Comment by MarkCiliaVincenti** [comment]
> Morning @MarkCiliaVincenti - Thanks for opening this PR, it is appreciated but we have discussed this change internally and decided against pulling it in.
> 
> The `AsyncKeyedLock` class we have is an intentionally naive implementation that has been used in a very high-traffic production system for almost 2 years without issue so we will stick with this for now and avoid pulling in an additional dependency.

Does this mean the same fate for https://github.com/dlcs/protagonist/pull/435 ?
I understand the "if it ain't broke..." but I wonder if you did run some benchmarks to see how much of a 'real life difference' it'd make.

**Pull request closed without merging**
